services:

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "7080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev"
    extends:
      file: common-config.yml
      service: network-deploy-service

  eurekaserver:
    image: "eureka:0.0.1-SNAPSHOT"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  actors:
    image: "actors:0.0.1-SNAPSHOT"
    container_name: actors-ms
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "actors"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  movies:
    image: "movies:0.0.1-SNAPSHOT"
    container_name: movies-ms
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "movies"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  actor-movie:
    image: "actor-movie:0.0.1-SNAPSHOT"
    container_name: actor-movie-ms
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      eurekaserver:
        condition: service_healthy
      movies:
        condition: service_healthy
      actors:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "actor-movie"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  gatewayserver:
    image: "gateway:0.0.1-SNAPSHOT"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on:
      actors:
        condition: service_healthy
      movies:
        condition: service_healthy
      actor-movie:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
    extends:
      file: common-config.yml
      service: microservice-eureka-config


networks:
  code-challenge:
    driver: "bridge"